name: cr_logger_example
description: Demonstrates how to use the cr_logger plugin.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cr_logger:
    path: ../

  dio: 4.0.6
  chopper: 5.1.0
  logger: ^1.1.0
  flutter_dropzone: ^3.0.5
  share_plus: 6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Epilogue
      fonts:
        - asset: fonts/Epilogue-Medium.ttf
        - asset: fonts/Epilogue-Regular.ttf