name: cr_logger
description: Powerful logging plugin. Supports android, ios and web platforms.

version: 2.3.0
homepage: https://github.com/Cleveroad/cr_logger

environment:
  sdk: ">=2.19.2 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^0.13.0

  # MIT
  cr_json_widget: ^1.1.0

  # Network
  # MIT
  dio: ^5.0.0
  # MIT
  chopper: ^6.1.0
  # MIT
  logger: ^1.1.0

  # BSD
  package_info_plus: ^3.0.0

  # MIT
  uuid: ^3.0.0

  # MIT
  app_settings: ^4.2.0

  # BSD
  path_provider: ^2.0.0
  # BSD-3-Clause
  path: ^1.8.2

  # MIT
  inspector: ^1.1.0

  # BSD-3-Clause
  shared_preferences: ^2.0.0
  # MIT
  split_view: ^3.2.0

  # unknown
  # https://pub.dev/packages/synchronized/license
  synchronized: ^3.0.0

  # BSD-3-Clause
  js: ^0.6.0

  # BSD-3-Clause
  # https://stackoverflow.com/a/70757512
  platform: ^3.1.0

  # Apache-2.0
  infinite_scroll_pagination: ^3.2.0
  # MIT
  worker_manager: ^5.0.0

  # BSD-2-Clause
  sqflite: ^2.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # MIT
  dart_code_metrics: ^5.6.0
  flutter_lints: ^2.0.0

  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Epilogue
      fonts:
        - asset: fonts/Epilogue-Medium.ttf
        - asset: fonts/Epilogue-Regular.ttf

  plugin:
    platforms:
      android:
        package: com.cleveroad.cr_logger.cr_logger
        pluginClass: CrLoggerPlugin
      ios:
        pluginClass: CrLoggerPlugin
      web:
        pluginClass: CrLoggerWeb
        fileName: cr_logger_web.dart

