name: cr_logger
description: Powerfull logging plugin. Supports android, ios and web platforms.

version: 0.9.13
homepage: https://github.com/Cleveroad/cr_logger

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^0.13.4
  # MIT
  cr_json_widget: ^0.9.0

  # Network
  # MIT
  dio: ^4.0.0
  # MIT
  chopper: ^4.0.0
  # MIT
  logger: ^1.1.0

  # BSD
  package_info_plus: ^1.0.6

  # MIT
  uuid: ^3.0.5

  # MIT
  app_settings: ^4.1.1

  # BSD
  path_provider: ^2.0.5

  # MIT
  inspector: ^1.1.1

  # MIT
  split_view: ^3.1.0

  # unknown
  # https://pub.dev/packages/synchronized/license
  synchronized: ^3.0.0

  # BSD-3-Clause
  js: ^0.6.3

  # BSD-3-Clause
  # https://stackoverflow.com/a/70757512
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # MIT
  dart_code_metrics: ^4.3.3
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Epilogue
      fonts:
        - asset: fonts/Epilogue-Medium.ttf
        - asset: fonts/Epilogue-Regular.ttf

  plugin:
    platforms:
      android:
        package: com.cleveroad.cr_logger.cr_logger
        pluginClass: CrLoggerPlugin
      ios:
        pluginClass: CrLoggerPlugin
      web:
        pluginClass: CrLoggerWeb
        fileName: cr_logger_web.dart

